### ISSUE TITLE
Installation - AttributeError: module 'pyto' has no attribute 'spatial'

### ISSUE THREAD

**Issue by nairouzshehata** [vladanl/Pyto#4]
Hello,
Thank you for this great package!

I tried to clone the repo then cd to pyto and python setup.py install
Also tried to export PYTHONPATH=/path/to/cloned/pyto:$PYTHONPATH
when I try python then import pyto I get

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/cloned/pyto/pyto/__init__.py", line 27, in <module>
    from . import spatial
  File "//path/to/cloned/pyto/pyto/spatial/__init__.py", line 10, in <module>
    from . import test
  File "//path/to/cloned/pyto/pyto/spatial/test/__init__.py", line 10, in <module>
    from .test_coloc_functions import TestColocFunctions
  File "//path/to/cloned/pyto/pyto/spatial/test/test_coloc_functions.py", line 18, in <module>
    import pyto.spatial.coloc_functions as col_func
AttributeError: module 'pyto' has no attribute 'spatial'

Even though I checked and spatial exists in the pyto/pyto folder and so does coloc_functions.py in spatial
I've used conda to create the enviornment with python 3.6

Looking forward to your response.

**Comment by vladanl** [comment]
Thank you for your report.

Frankly, I don't understand why you get the error. As you said, pyto.spatial.coloc_functions exists. I'm using my development version code essentially every day, there is no error like the one you reported and there were no changes in the code leading to the error.

Could I ask you to make sure that your PYTHONPATH contains (or just for testing purposes starts with) /path/to/cloned/pyto.

The error contains both /path/to/cloned/pyto and //path/to/cloned/pyto. I wonder the double slash at the beginning might be a problem.

On a side note, you can use any path instead of  "/path/to/cloned/".

If the above does not work, please try the following workarounds:  
- Comment out line 10 in /path/to/cloned/pyto/pyto/spatial/init.py, it's just used for testing
- Comment out line 27 in /path/to/cloned/pyto/pyto/init.py, you probably do not need the pyto.spatial module at all, because this is only used for the colocalization analysis like we presented in [https://www.science.org/doi/10.1126/sciadv.abe6204](https://www.science.org/doi/10.1126/sciadv.abe6204)

Let me know please

**Comment by nairouzshehata** [comment]
It's strange but when I used a different directory so did `cd ..` then `git clone` and `install setup` it worked. Not sure what the directory had to do with anything.
Thank you for your prompt reply and thank you for sharing this great repo.
